# -*- coding: utf-8 -*-
"""Per-row skill mapping for the Monimo golden dataset (sheet '2) DATA').

Each dataset row (seq) maps to exactly one skill:
  name  : skill identifier (snake_case, aligned with tool naming convention)
  desc  : leading "무엇을 + 언제" sentence of the SKILL.md description.
          The generator appends 대표 발화 예시 automatically.
  tools : required_tools — mock MCP tools the skill orchestrates (in call order)
  group : body-template group in generate_skills.py (instruction/exception/문구 templates)
"""

S = lambda name, desc, tools, group: dict(name=name, desc=desc, tools=tools, group=group)

SKILL_MAP = {
    # ── 금융 > 검색 > 메뉴 ─────────────────────────────────────────────
    "001": S("menu_location_search",
             "사용자가 모니모 앱의 특정 기능·메뉴가 어디 있는지 찾을 때 사용합니다. 메뉴 위치와 앱 내 이동 경로 안내가 필요한 모든 질의에 적합합니다.",
             ["menu_search"], "menu"),
    "002": S("menu_ambiguity_clarify",
             "사용자가 '포인트 쓰는 곳'처럼 여러 메뉴에 해당할 수 있는 모호한 검색어로 질의할 때 사용합니다. 포인트 종류(갤러/모니머니/카드포인트 등) 확인 등 의도를 먼저 좁혀야 하는 경우에 적합합니다.",
             ["menu_search"], "menu_clarify"),
    "003": S("asset_menu_guide",
             "사용자가 통합자산(마이데이터) 조회 화면의 위치를 물을 때 사용합니다. 자산 메뉴 경로 안내와 마이데이터 연결 필요 여부 안내가 필요한 경우에 적합합니다.",
             ["menu_search"], "menu"),
    "004": S("customer_center_menu_guide",
             "사용자가 고객센터 메뉴 위치를 찾을 때 사용합니다. 고객센터 이동 경로와 FAQ/채팅상담/전화상담의 차이 설명이 필요한 경우에 적합합니다.",
             ["menu_search", "faq_search"], "menu"),
    "005": S("security_menu_guide",
             "사용자가 간편비밀번호 변경 등 인증·보안 설정 메뉴 위치를 물을 때 사용합니다. 설정/보안 메뉴 경로 안내와 본인인증 필요 가능성 안내가 필요한 경우에 적합합니다.",
             ["menu_search"], "menu"),

    # ── 비금융 > 이벤트 ────────────────────────────────────────────────
    "007": S("ongoing_event_list",
             "사용자가 현재 진행 중인 이벤트 목록을 물을 때 사용합니다. 이벤트명·기간·혜택 요약 리스트 제공이 필요한 경우에 적합합니다.",
             ["event_list_inquiry"], "event"),
    "008": S("company_event_list",
             "사용자가 삼성카드·삼성생명 등 특정 회사가 진행하는 이벤트 목록을 물을 때 사용합니다. 진행회사 필터 기준의 이벤트 조회에 적합합니다.",
             ["event_list_inquiry"], "event"),
    "009": S("monimo_event_detail",
             "사용자가 진행 중인 모니모 이벤트의 세부 내용(발표일, 응모 방법, 경품 등)을 물을 때 사용합니다.",
             ["event_list_inquiry", "event_detail_inquiry"], "event_detail"),
    "010": S("affiliate_event_detail",
             "사용자가 금융4사(생명/화재/카드/증권) 이벤트의 세부 내용이나 혜택 조건을 물을 때 사용합니다. 키워드 기반 이벤트 탐색 후 혜택 안내가 필요한 경우에 적합합니다.",
             ["event_list_inquiry", "event_detail_inquiry"], "event_detail"),
    "011": S("event_participation_check",
             "사용자가 특정 이벤트에 본인이 응모/참여했는지 물을 때 사용합니다.",
             ["event_list_inquiry", "event_participation_inquiry"], "event_participation"),
    "012": S("event_menu_path_guide",
             "사용자가 특정 이벤트 페이지를 어디서 볼 수 있는지 경로를 물을 때 사용합니다. 키워드에 맞는 이벤트 리스트와 확인 경로 안내에 적합합니다.",
             ["event_list_inquiry", "menu_search"], "event"),

    # ── 금융 > 검색 > 고객센터(FAQ) ───────────────────────────────────
    "014": S("customer_center_location",
             "사용자가 문의·문제 해결을 위해 고객센터 진입 경로를 찾을 때 사용합니다.",
             ["menu_search", "faq_search"], "menu"),
    "015": S("faq_feature_guide",
             "사용자가 자주 묻는 질문(FAQ)을 어디서 보는지, 스스로 해결 가능한 정보를 찾을 때 사용합니다. FAQ 메뉴 위치와 검색 기능 안내에 적합합니다.",
             ["menu_search", "faq_search"], "menu"),
    "016": S("consult_channel_guide",
             "사용자가 온라인상담·전화상담 등 상담 채널 간 차이를 비교하고 선택하려 할 때 사용합니다. 채널별 특징과 운영시간 차이 안내에 적합합니다.",
             ["faq_search"], "faq"),
    "017": S("customer_center_hours",
             "사용자가 고객센터 운영시간이나 지금 상담 가능한지를 물을 때 사용합니다.",
             ["faq_search"], "faq"),
    "018": S("affiliate_customer_center_guide",
             "사용자가 삼성생명·삼성화재 등 관계사 문의를 어디로 해야 하는지 헷갈릴 때 사용합니다. 관계사별 고객센터 구분과 연결 경로 안내에 적합합니다.",
             ["faq_search"], "faq"),
    "019": S("faq_search_support",
             "사용자가 특정 업무·서비스 관련 FAQ를 찾아 달라고 할 때 사용합니다. 관련 FAQ 카테고리 안내와 검색 키워드 추천에 적합합니다.",
             ["faq_search"], "faq"),

    # ── 금융 > 상품 정보 > 보험 ───────────────────────────────────────
    "022": S("insurance_coverage_inquiry",
             "사용자가 암보험 등 특정 보험상품의 보장내용을 확인하려 할 때 사용합니다. 생명/화재 보험 리스트와 주요 보장내용 요약 안내에 적합합니다.",
             ["product_search", "product_detail"], "product"),
    "023": S("insurance_recommend_by_condition",
             "사용자가 질병·사고 등 본인 상황을 이야기하며 보장받을 수 있는 보험을 찾을 때 사용합니다.",
             ["product_recommend", "product_detail"], "product_recommend"),
    "024": S("life_insurance_product_search",
             "사용자가 삼성생명의 특정 보험상품(예: 핵심건강보험)을 지목해 물을 때 사용합니다.",
             ["product_search", "product_detail"], "product"),
    "025": S("fire_insurance_product_search",
             "사용자가 삼성화재의 특정 보험상품이나 키워드(예: AI 보험)로 상품을 찾을 때 사용합니다.",
             ["product_search", "product_detail"], "product"),
    "026": S("insurance_premium_inquiry",
             "사용자가 보험 가입 시 보험료가 얼마인지 물을 때 사용합니다. 가입 가능 상품과 연령대별 예상 보험료 제시에 적합합니다.",
             ["product_search", "insurance_premium_estimate"], "premium"),
    "027": S("insurance_cancel_menu_guide",
             "사용자가 특정 보험상품의 계약 해지를 원할 때 사용합니다. 해지 가능한 메뉴 안내와 바로가기 제공에 적합합니다.",
             ["menu_search"], "menu"),

    # ── 금융 > 상품 정보 > 연금 ───────────────────────────────────────
    "029": S("pension_product_search",
             "사용자가 IRP 등 연금상품을 간편하게 탐색하려 할 때 사용합니다. 모니모 내 가입 가능한 연금상품군과 특징 요약에 적합합니다.",
             ["product_search"], "product"),
    "030": S("pension_product_detail",
             "사용자가 특정 연금상품(예: 증권 연금저축)의 정보를 확인하려 할 때 사용합니다.",
             ["product_search", "product_detail"], "product"),
    "031": S("pension_consult_guide",
             "연금을 잘 모르는 사용자가 무엇에 가입해야 할지 전반적인 상담을 원할 때 사용합니다. 가입 목적 추가 질의 후 적절한 상품 안내에 적합합니다.",
             ["product_recommend"], "product_recommend"),

    # ── 금융 > 상품 정보 > 대출 ───────────────────────────────────────
    "033": S("loan_product_search",
             "사용자가 대출상품 목록을 간편하게 탐색하려 할 때 사용합니다. 모니모 내 가입 가능한 대출상품 리스트와 요약 안내에 적합합니다.",
             ["product_search"], "product"),
    "034": S("loan_lowest_rate_search",
             "사용자가 이자율이 가장 낮은 대출 등 특정 조건의 대출상품을 찾을 때 사용합니다. 최저 이자율 기준 정렬 안내에 적합합니다.",
             ["product_search"], "product"),
    "035": S("loan_product_detail",
             "사용자가 삼성생명 보험계약대출 등 특정 대출상품 정보를 확인하려 할 때 사용합니다.",
             ["product_search", "product_detail"], "product"),
    "036": S("loan_first_time_consult",
             "대출이 처음인 사용자가 어떤 대출을 받아야 할지 상담을 원할 때 사용합니다. 대출 목적 파악 후 맞춤 상품 안내에 적합합니다.",
             ["product_recommend"], "product_recommend"),

    # ── 금융 > 상품 정보 > 카드 ───────────────────────────────────────
    "038": S("card_product_benefit_inquiry",
             "사용자가 특정 카드가 어떤 상품인지, 핵심 혜택이 무엇인지 물을 때 사용합니다.",
             ["product_search", "product_detail"], "product"),
    "039": S("card_benefit_condition_inquiry",
             "사용자가 특정 카드 혜택이 언제·어떤 조건에서 적용되는지 물을 때 사용합니다. 대상 가맹점, 이용 조건, 할인 제외 대상 안내에 적합합니다.",
             ["product_detail"], "product"),
    "040": S("card_product_compare",
             "사용자가 두 개 이상의 카드를 비교하려 할 때 사용합니다. 카드별 특징과 비교표 제공에 적합합니다.",
             ["product_search", "product_compare"], "product_compare"),
    "041": S("card_product_recommend",
             "사용자가 조건 없이 카드 추천을 원할 때 사용합니다. 원하는 혜택을 추가 질문한 뒤 상품을 안내하는 경우에 적합합니다.",
             ["product_recommend"], "product_recommend"),
    "042": S("card_recommend_by_benefit",
             "사용자가 전기차 충전 할인처럼 특정 혜택 기준으로 카드 추천을 요청할 때 사용합니다.",
             ["product_recommend"], "product_recommend"),
    "043": S("card_issuance_eligibility",
             "사용자가 가족카드 등 카드 발급 가능 여부를 물을 때 사용합니다.",
             ["faq_search", "product_detail"], "faq"),
    "044": S("card_application_guide",
             "사용자가 카드를 만들려면 어디로 가야 하는지 신청 방법을 물을 때 사용합니다.",
             ["menu_search", "faq_search"], "menu"),

    # ── 금융 > 상품 정보 > 투자 ───────────────────────────────────────
    "047": S("stock_overview_inquiry",
             "사용자가 기업명만 입력하는 등 특정 종목의 전반 정보를 찾을 때 사용합니다. 회사정보·최근 뉴스·주가를 함께 안내하는 경우에 적합합니다.",
             ["stock_item_inquiry"], "stock"),
    "048": S("stock_price_inquiry",
             "사용자가 특정 회사의 주가·시세를 물을 때 사용합니다.",
             ["stock_item_inquiry"], "stock"),
    "049": S("popular_stock_inquiry",
             "사용자가 지금 인기 있는 주식 종목을 물을 때 사용합니다. 국내/해외 인기 Top5 안내에 적합합니다.",
             ["stock_ranking_inquiry"], "stock_ranking"),
    "050": S("stock_volume_ranking",
             "사용자가 거래량·거래대금이 많은 종목 순위를 물을 때 사용합니다.",
             ["stock_ranking_inquiry"], "stock_ranking"),
    "051": S("sector_stock_search",
             "사용자가 제약 등 특정 업종·섹터의 투자할 만한 종목을 찾을 때 사용합니다.",
             ["stock_ranking_inquiry"], "stock_ranking"),
    "052": S("unlisted_stock_inquiry",
             "사용자가 비상장 회사(예: 마켓컬리)의 주가를 물을 때 사용합니다. 비상장 안내와 상장 종목 확인 제안에 적합합니다.",
             ["stock_item_inquiry"], "stock_unlisted"),

    # ── 금융 > 금융 정보 > 금융 용어 사전 ─────────────────────────────
    "054": S("glossary_basic_finance",
             "사용자가 DSR 등 기본 금융용어의 의미를 물을 때 사용합니다. 정의와 활용 예시 설명에 적합합니다.",
             ["glossary_search"], "glossary"),
    "055": S("glossary_insurance_term",
             "사용자가 면책기간 등 보험계약 관련 용어를 물을 때 사용합니다. 정의·필요 이유·상품별 차이 유의사항 설명에 적합합니다.",
             ["glossary_search"], "glossary"),
    "056": S("glossary_card_payment_term",
             "사용자가 리볼빙 등 카드·결제 용어를 물을 때 사용합니다.",
             ["glossary_search"], "glossary"),
    "057": S("glossary_investment_term",
             "사용자가 ETF와 펀드의 차이 등 투자·펀드 용어를 물을 때 사용합니다.",
             ["glossary_search"], "glossary"),
    "058": S("glossary_loan_term",
             "사용자가 고정금리·변동금리 차이 등 대출 용어를 물을 때 사용합니다.",
             ["glossary_search"], "glossary"),
    "059": S("glossary_tax_term",
             "사용자가 세액공제·소득공제 차이 등 세금·절세 용어를 물을 때 사용합니다.",
             ["glossary_search"], "glossary"),
    "060": S("glossary_mydata_term",
             "사용자가 마이데이터 등 자산관리·디지털 금융 개념을 물을 때 사용합니다.",
             ["glossary_search"], "glossary"),
    "061": S("glossary_easy_payment_term",
             "사용자가 선불전자지급수단 등 간편결제·포인트 용어를 물을 때 사용합니다. 모니머니 등 대표 예시와 충전 구조 안내에 적합합니다.",
             ["glossary_search"], "glossary"),
    "062": S("glossary_economic_indicator",
             "사용자가 기준금리와 대출이자의 관계 등 금융지표·경제용어를 물을 때 사용합니다.",
             ["glossary_search"], "glossary"),
    "063": S("glossary_abbreviation",
             "사용자가 APR 등 약어·영문 금융용어의 뜻을 물을 때 사용합니다. 풀네임과 개념 설명에 적합합니다.",
             ["glossary_search"], "glossary"),

    # ── 금융 > 금융 정보 > 금융계산기 ────────────────────────────────
    "065": S("calc_loan_repayment",
             "사용자가 대출 시 월 상환금이 얼마인지 계산을 원할 때 사용합니다. 원금·금리·기간·상환방식 기반 월 납입액 계산에 적합합니다.",
             ["financial_calculator"], "calculator"),
    "066": S("calc_savings_maturity",
             "사용자가 적금·예금 만기 예상 금액 계산을 원할 때 사용합니다. 월 납입금·기간·금리 기반 계산에 적합합니다.",
             ["financial_calculator"], "calculator"),
    "067": S("calc_dsr",
             "사용자가 본인 DSR이 얼마나 나오는지 계산을 원할 때 사용합니다. 연소득과 기존 대출 원리금 기반 계산에 적합합니다.",
             ["financial_calculator"], "calculator"),
    "068": S("calc_card_installment",
             "사용자가 카드 할부 시 월 납부액 계산을 원할 때 사용합니다. 무이자 여부 확인 후 월 예상 납부액 제공에 적합합니다.",
             ["financial_calculator"], "calculator"),
    "069": S("calc_pension_receipt",
             "사용자가 연금 예상 수령액 계산을 원할 때 사용합니다. 월 납입금·기간·수익률 기반 단순 예상치 제공에 적합합니다.",
             ["financial_calculator"], "calculator"),
    "070": S("calc_exchange_rate",
             "사용자가 외화 금액을 원화로 환산해 달라고 할 때 사용합니다. 현재 환율 기준 계산과 매매기준/카드환율 차이 설명에 적합합니다.",
             ["financial_calculator"], "calculator"),
    "071": S("calc_income_tax",
             "사용자가 연봉 대비 실수령액 계산을 원할 때 사용합니다. 국민연금·건강보험·소득세 반영 안내에 적합합니다.",
             ["financial_calculator"], "calculator"),
    "072": S("calc_investment_return",
             "사용자가 투자 수익률에 따른 수익금 계산을 원할 때 사용합니다. 수익금과 수익률 구분 설명에 적합합니다.",
             ["financial_calculator"], "calculator"),
    "073": S("calc_insurance_premium",
             "사용자가 보험 가입 시 보험료가 대략 얼마인지 물을 때 사용합니다. 연령·성별·보장범위에 따라 달라진다는 안내와 예상치 제공에 적합합니다.",
             ["insurance_premium_estimate"], "premium"),
    "074": S("calc_target_saving",
             "사용자가 목표 금액을 모으기 위한 월 저축액 계산을 원할 때 사용합니다. 목표금액·기간·예상 수익률 기반 계산에 적합합니다.",
             ["financial_calculator"], "calculator"),

    # ── 금융 > 모니모 > 자산 ─────────────────────────────────────────
    "076": S("mydata_asset_guide",
             "사용자가 자산(마이데이터) 화면에서 무엇을 할 수 있는지 등 일반적인 질문을 할 때 사용합니다.",
             ["asset_summary_inquiry", "menu_search"], "menu"),
    "077": S("spending_total_inquiry",
             "사용자가 이번 달 등 기준월의 총 소비금액을 물을 때 사용합니다. 카테고리별 금액과 전월 대비 비교 안내에 적합합니다.",
             ["spending_summary_inquiry"], "spending"),
    "078": S("spending_by_card_inquiry",
             "사용자가 특정 월에 특정 카드로 얼마 썼는지 물을 때 사용합니다. 카드별 소비금액 합산 조회에 적합합니다.",
             ["spending_by_card_inquiry"], "spending"),
    "079": S("budget_status_inquiry",
             "사용자가 설정한 한 달 예산 대비 현재 소비 현황을 물을 때 사용합니다. 예산·소비 총합·초과/잔여 금액 안내에 적합합니다.",
             ["budget_inquiry", "spending_summary_inquiry"], "spending"),
    "080": S("budget_update_request",
             "사용자가 설정된 한 달 예산 금액을 변경하려 할 때 사용합니다.",
             ["budget_inquiry", "budget_update"], "action_confirm"),
    "081": S("monthly_spending_inquiry",
             "사용자가 특정 월의 소비금액 총합과 결제수단별 내역을 물을 때 사용합니다.",
             ["spending_summary_inquiry"], "spending"),
    "082": S("monthly_top_category_inquiry",
             "사용자가 특정 월에 어느 업종에서 가장 많이 썼는지 물을 때 사용합니다. 카테고리별 소비 비중 분석에 적합합니다.",
             ["spending_category_inquiry"], "spending"),
    "083": S("monthly_card_usage_ranking",
             "사용자가 특정 월에 가장 많이/적게 쓴 카드가 무엇인지 물을 때 사용합니다.",
             ["spending_by_card_inquiry"], "spending"),
    "084": S("food_spending_inquiry",
             "사용자가 기준월의 식비 지출 금액을 물을 때 사용합니다. 외식업종 소비금액 총합 안내에 적합합니다.",
             ["spending_category_inquiry"], "spending"),
    "085": S("random_food_recommend",
             "사용자가 오늘 뭐 먹을지 메뉴 추천을 요청할 때 사용합니다. '오늘뭐먹지' 화면 이동 배너 제공에 적합합니다.",
             ["menu_search"], "menu"),
    "086": S("food_spending_detail",
             "사용자가 기준월에 무엇을 제일 많이 먹었는지 등 식비 상세 분석을 물을 때 사용합니다. 외식업종 중 최다 소비 카테고리 안내에 적합합니다.",
             ["spending_category_inquiry"], "spending"),
    "087": S("daily_payment_history",
             "사용자가 특정 일자의 결제이력·명세서 기준 소비금액을 물을 때 사용합니다.",
             ["payment_history_inquiry"], "spending"),
    "088": S("weekly_spending_inquiry",
             "사용자가 지난주 등 주차 기준의 총 소비금액을 물을 때 사용합니다.",
             ["spending_summary_inquiry"], "spending"),
    "089": S("weekly_category_ranking",
             "사용자가 지난주 어디에 돈을 제일 많이 썼는지 등 주차 기준 카테고리별 소비 순위를 물을 때 사용합니다.",
             ["spending_category_inquiry"], "spending"),
    "090": S("weekly_daily_spending",
             "사용자가 지난주 언제(어느 요일/일자) 돈을 가장 많이 썼는지 물을 때 사용합니다.",
             ["spending_summary_inquiry"], "spending"),
    "091": S("spending_scope_setting_guide",
             "사용자가 소비금액 집계에 계좌이체·포인트 사용내역을 포함/제외하는 방법을 물을 때 사용합니다. 토글 설정 방법 안내에 적합합니다.",
             ["menu_search"], "menu"),

    # ── 금융 > 모니모 > 마이통장 ─────────────────────────────────────
    "093": S("account_balance_inquiry",
             "사용자가 모니모 마이통장(KB국민은행 파킹통장, 삼성증권 CMA 등)의 잔액을 물을 때 사용합니다.",
             ["account_list_inquiry", "account_balance_inquiry"], "account"),
    "094": S("account_transaction_inquiry",
             "사용자가 특정 일자의 통장 거래내역을 물을 때 사용합니다.",
             ["account_list_inquiry", "account_transaction_inquiry"], "account"),
    "095": S("account_interest_receive",
             "사용자가 '오늘 이자받기 해줘'처럼 매일 이자받기 실행을 요청할 때 사용합니다. KB파킹통장/삼성증권 CMA 대상 이자받기 실행에 적합합니다.",
             ["account_list_inquiry", "account_interest_receive"], "account_action"),
    "096": S("account_expected_interest",
             "사용자가 현재 통장 잔액 기준으로 받을 수 있는 예상 이자를 물을 때 사용합니다.",
             ["account_list_inquiry", "account_interest_inquiry"], "account"),
    "097": S("account_interest_simulation",
             "사용자가 특정 금액을 넣어두면 이자를 얼마나 받는지 시뮬레이션을 원할 때 사용합니다.",
             ["account_list_inquiry", "account_interest_inquiry"], "account"),
    "098": S("account_interest_rate_inquiry",
             "사용자가 현재 본인 통장의 이자율(챌린지 달성에 따른 우대금리 포함)을 물을 때 사용합니다.",
             ["account_list_inquiry", "account_interest_inquiry"], "account"),

    # ── 비금융 > 모니모 > 젤리 ───────────────────────────────────────
    "100": S("jelly_balance_inquiry",
             "사용자가 현재 보유한 젤리 개수(일반/스페셜)를 물을 때 사용합니다.",
             ["jelly_balance_inquiry"], "jelly"),
    "101": S("jelly_conversion_rate_inquiry",
             "사용자가 젤리를 모니머니로 바꾸면 얼마인지, 적립 비율·레벨을 물을 때 사용합니다. 회원등급 산정 후 전환 비율 안내에 적합합니다.",
             ["jelly_balance_inquiry", "jelly_level_inquiry"], "jelly"),
    "102": S("jelly_exchange_request",
             "사용자가 보유 젤리를 모니머니로 교환해 달라고 요청할 때 사용합니다. 보유 젤리 확인 후 교환 실행에 적합합니다.",
             ["jelly_balance_inquiry", "jelly_exchange_request"], "action_confirm"),
    "104": S("jelly_challenge_guide",
             "사용자가 젤리 챌린지가 무엇인지, 신청은 어떻게 하는지 등 서비스 전반을 물을 때 사용합니다.",
             ["faq_search", "challenge_list_inquiry"], "faq"),
    "105": S("jelly_challenge_status",
             "사용자가 현재 참여 중인 챌린지의 달성 현황(예: 걷기 챌린지 달성일수)을 물을 때 사용합니다.",
             ["challenge_status_inquiry"], "jelly"),
    "106": S("jelly_challenge_available",
             "사용자가 지금 신청 가능한 챌린지 목록과 기간을 물을 때 사용합니다. 신청 가능 기간(매월 16일~말일) 내 조회에 적합합니다.",
             ["challenge_list_inquiry"], "jelly"),
    "107": S("jelly_challenge_apply_period_guide",
             "사용자가 참여 가능한 챌린지를 물었지만 현재 신청 가능 기간이 아닐 때 사용합니다. 신청 가능 기간(매월 16일~말일) 안내와 챌린지 메인 화면 이동에 적합합니다.",
             ["challenge_list_inquiry"], "jelly"),
    "109": S("jelly_earning_summary",
             "사용자가 지난달 등 특정 월에 젤리를 몇 개 모았는지 물을 때 사용합니다.",
             ["jelly_history_inquiry"], "jelly"),
    "110": S("jelly_investment_inquiry",
             "젤리투자 이용 중인 사용자가 지금까지의 누계 젤리 투자금액을 물을 때 사용합니다.",
             ["jelly_investment_inquiry"], "jelly"),
    "111": S("jelly_earning_history",
             "사용자가 특정 월의 젤리 적립내역(적립일자·이력·일반/스페셜 구분)을 물을 때 사용합니다.",
             ["jelly_history_inquiry"], "jelly"),

    # ── 비금융 > 모니모 > 관심소식 ───────────────────────────────────
    "113": S("popular_content_inquiry",
             "사용자가 조회수 높은 인기소식을 물을 때 사용합니다.",
             ["content_list_inquiry"], "content"),
    "114": S("interest_content_recommend",
             "사용자가 본인이 설정한 관심분야 기준의 오늘의 관심소식 추천을 원할 때 사용합니다.",
             ["interest_topic_inquiry", "content_list_inquiry"], "content"),
    "115": S("topic_content_inquiry",
             "사용자가 여행맛집 등 특정 관심분야 컨텐츠를 보여 달라고 할 때 사용합니다.",
             ["content_list_inquiry"], "content"),
    "116": S("content_detail_inquiry",
             "사용자가 특정 관심소식 컨텐츠의 내용이 무엇인지 물을 때 사용합니다. 컨텐츠 본문 요약 안내에 적합합니다.",
             ["content_list_inquiry", "content_detail_inquiry"], "content"),
    "117": S("interest_topic_inquiry",
             "사용자가 본인이 설정한 관심분야 목록을 확인하려 할 때 사용합니다.",
             ["interest_topic_inquiry"], "content"),
    "118": S("interest_topic_update",
             "사용자가 관심분야를 추가·변경하고 싶을 때 사용합니다. 관심분야 설정화면 이동 안내에 적합합니다.",
             ["interest_topic_inquiry", "interest_topic_update"], "action_confirm"),

    # ── 금융 > 모니모 > 모니머니 ─────────────────────────────────────
    "120": S("monimoney_usage_guide",
             "사용자가 모니머니가 무엇이고 어떻게 사용하는지 물을 때 사용합니다. 충전/송금/결제/투자/보험료납입 활용 안내에 적합합니다.",
             ["faq_search"], "faq"),
    "121": S("monimoney_policy_guide",
             "사용자가 모니머니 사용 시 한도·조건·유의사항 등을 물을 때 사용합니다.",
             ["faq_search", "monimoney_info_inquiry"], "faq"),
    "122": S("monimoney_balance_inquiry",
             "사용자가 현재 보유한 모니머니 잔액을 물을 때 사용합니다.",
             ["monimoney_balance_inquiry"], "monimoney"),
    "123": S("monimoney_history_inquiry",
             "사용자가 특정 월의 모니머니 입출금·적립·차감 내역을 물을 때 사용합니다.",
             ["monimoney_history_inquiry"], "monimoney"),
    "124": S("monimoney_transaction_reason",
             "사용자가 특정 모니머니 이용 건(입금/출금/결제)이 왜 발생했는지 사유를 물을 때 사용합니다.",
             ["monimoney_history_inquiry"], "monimoney"),
    "125": S("monimoney_limit_expiry_inquiry",
             "사용자가 모니머니 출금한도·유효기간 등 관리화면 노출 데이터를 물을 때 사용합니다.",
             ["monimoney_info_inquiry"], "monimoney"),
    "126": S("monimoney_transfer_to_account",
             "사용자가 남은 모니머니를 본인 통장으로 보내 달라고 요청할 때 사용합니다. 출금 계좌 확인 후 이체 실행에 적합합니다.",
             ["monimoney_balance_inquiry", "monimoney_withdraw"], "action_confirm"),
    "127": S("monimoney_withdraw_all",
             "사용자가 보유 모니머니 전액 출금을 요청할 때 사용합니다. 수취 계좌·금액 확인 후 출금 실행에 적합합니다.",
             ["monimoney_balance_inquiry", "monimoney_withdraw"], "action_confirm"),
    "128": S("monimoney_withdraw_restriction",
             "사용자가 모니머니 출금이 안 되는 사유를 물을 때 사용합니다. 출금 요청 건 확인 후 불가 사유 안내에 적합합니다.",
             ["monimoney_history_inquiry", "monimoney_restriction_inquiry"], "monimoney"),

    # ── 비금융 > 모니모 > 걷기 ───────────────────────────────────────
    "130": S("walking_steps_inquiry",
             "사용자가 오늘 지금까지 몇 보 걸었는지 걸음수를 물을 때 사용합니다.",
             ["walking_steps_inquiry"], "benefit_game"),
    "131": S("walking_mission_achievement",
             "사용자가 특정 월 기준 걷기 미션(예: 5,000보) 달성 횟수를 물을 때 사용합니다.",
             ["walking_mission_inquiry"], "benefit_game"),

    # ── 비금융 > 모니모 > 빙고게임 ───────────────────────────────────
    "133": S("bingo_guide",
             "사용자가 빙고게임이 무엇인지 이용방법·정책을 물을 때 사용합니다. 미션 개수·리워드·오픈 기간 안내에 적합합니다.",
             ["faq_search", "bingo_mission_inquiry"], "faq"),
    "134": S("bingo_start_request",
             "미참여 사용자가 빙고게임 참여를 요청할 때 사용합니다. 개인정보 수집·이용 동의 확인 후 빙고 게임 화면 랜딩에 적합합니다.",
             ["bingo_status_inquiry", "bingo_start"], "action_confirm"),
    "135": S("bingo_progress_inquiry",
             "사용자가 빙고 완성까지 몇 개 남았는지, 보너스 스티커 보유 여부 등 참여 현황을 물을 때 사용합니다.",
             ["bingo_status_inquiry"], "benefit_game"),
    "136": S("bingo_last_month_result",
             "사용자가 지난달 빙고 달성 여부와 보상 젤리를 물을 때 사용합니다.",
             ["bingo_status_inquiry"], "benefit_game"),
    "137": S("bingo_mission_guide",
             "사용자가 빙고 달성을 위한 미션별 달성 기준·방법을 물을 때 사용합니다.",
             ["bingo_mission_inquiry"], "benefit_game"),

    # ── 비금융 > 모니모 > 모니스쿨 ───────────────────────────────────
    "139": S("monischool_guide",
             "사용자가 모니스쿨이 어떤 서비스인지 물을 때 사용합니다. 이벤트 유형·참여 방법·혜택 안내에 적합합니다.",
             ["faq_search"], "faq"),
    "140": S("monischool_status_inquiry",
             "사용자가 이번 달 모니스쿨 참여 현황(참여 여부·정답 여부·잔여 횟수)을 물을 때 사용합니다.",
             ["monischool_status_inquiry"], "benefit_game"),
    "141": S("monischool_quiz_inquiry",
             "사용자가 지금 응시할 수 있는 모니스쿨 문제가 무엇인지 물을 때 사용합니다.",
             ["monischool_quiz_inquiry"], "benefit_game"),
    "142": S("monischool_quiz_hint",
             "사용자가 모니스쿨 특정 교시 문제의 힌트를 요청할 때 사용합니다.",
             ["monischool_quiz_inquiry", "monischool_hint_inquiry"], "benefit_game"),
    "143": S("monischool_answer_submit",
             "사용자가 모니스쿨 문제의 답안을 제출하려 할 때 사용합니다. 교시·답안 확인 후 제출 실행에 적합합니다.",
             ["monischool_quiz_inquiry", "monischool_answer_submit"], "action_confirm"),

    # ── 비금융 > 모니모 > 친구초대 ───────────────────────────────────
    "145": S("referral_benefit_guide",
             "사용자가 친구초대를 하면 무엇이 좋은지 혜택·정책을 물을 때 사용합니다.",
             ["faq_search"], "faq"),
    "146": S("referral_code_inquiry",
             "사용자가 본인의 친구초대 코드·링크를 확인하려 할 때 사용합니다.",
             ["referral_code_inquiry"], "benefit_game"),
    "147": S("referral_status_inquiry",
             "사용자가 지금까지 친구초대에 몇 명 성공했는지 진행 현황을 물을 때 사용합니다.",
             ["referral_status_inquiry"], "benefit_game"),

    # ── 비금융 > 모니모 > 오늘의 소식 ────────────────────────────────
    "149": S("daily_newsletter_inquiry",
             "사용자가 오늘의 주요 소식(뉴스레터) 요약을 요청할 때 사용합니다.",
             ["daily_news_inquiry"], "news"),
    "150": S("closing_brief_inquiry",
             "사용자가 오늘의 증권 마감브리핑을 요청할 때 사용합니다. 나스닥/S&P 등 지수 등락 요약에 적합합니다.",
             ["daily_news_inquiry"], "news"),
    "151": S("walk_index_weather_inquiry",
             "지역을 설정해 둔 사용자가 현재 날씨·산책지수를 물을 때 사용합니다. 설정 지역 기준 날씨/기온/대기 수준 안내에 적합합니다.",
             ["weather_inquiry"], "weather"),
    "152": S("walk_index_weather_multiturn",
             "지역을 설정하지 않은 사용자가 날씨·산책지수를 물을 때 사용합니다. 기준 지역을 되물은 뒤 해당 지역 날씨를 안내하는 멀티턴 처리에 적합합니다.",
             ["weather_inquiry"], "weather_multiturn"),

    # ── 금융 > 모니모 > 송금 ─────────────────────────────────────────
    "154": S("transfer_account_inquiry",
             "사용자가 특정인에게 송금하려 할 때 최근 송금 이력·즐겨찾기 기반 송금 가능 계좌 목록을 확인하는 경우 사용합니다.",
             ["transfer_account_inquiry"], "transfer"),
    "155": S("transfer_history_inquiry",
             "사용자가 지난주 등 특정 기간의 송금내역(전체/보낸/받은)을 물을 때 사용합니다.",
             ["transfer_history_inquiry"], "transfer"),

    # ── 비금융 > 모니모 > 이달의 미션 ────────────────────────────────
    "157": S("monthly_mission_status",
             "사용자가 이번 달 이달의 미션을 몇 개 달성했는지 참여 현황을 물을 때 사용합니다.",
             ["monthly_mission_status_inquiry"], "benefit_game"),
    "158": S("monthly_mission_list",
             "사용자가 지금 참여할 수 있는 이달의 미션 목록을 물을 때 사용합니다. 미달성 미션 안내에 적합합니다.",
             ["monthly_mission_list_inquiry"], "benefit_game"),
    "159": S("monthly_mission_participate",
             "사용자가 특정 이달의 미션(예: 오늘의 영어 확인하기) 수행을 요청할 때 사용합니다. 미션 내용 안내와 랜딩 화면 제공에 적합합니다.",
             ["monthly_mission_list_inquiry", "monthly_mission_participate"], "action_confirm"),

    # ── 금융 > 삼성금융 > 보험금 청구 ────────────────────────────────
    "161": S("insurance_claim_status_inquiry",
             "사용자가 진행 중인 보험금 청구가 어떻게 되어 가는지 물을 때 사용합니다. 가장 최근 청구 건의 진행현황 안내에 적합합니다.",
             ["insurance_claim_status_inquiry"], "claims"),
    "162": S("insurance_claim_status_by_month",
             "사용자가 특정 월에 청구한 보험금의 진행현황을 물을 때 사용합니다.",
             ["insurance_claim_status_inquiry"], "claims"),
    "163": S("insurance_claim_history_period",
             "사용자가 작년 1년 등 특정 기간의 보험금 청구내역 전체를 물을 때 사용합니다.",
             ["insurance_claim_status_inquiry"], "claims"),
    "164": S("insurance_claim_by_product",
             "사용자가 암보험 등 특정 상품 기준의 보험금 청구내역을 물을 때 사용합니다.",
             ["insurance_claim_status_inquiry"], "claims"),
    "165": S("insurance_claim_submit",
             "사용자가 보험금 청구 실행을 요청할 때 사용합니다. 모니모에서 직접 청구는 미지원이므로 청구 가능한 회사(생명/화재) 화면으로 이동시키는 경우에 적합합니다.",
             ["insurance_contract_inquiry", "insurance_claim_submit"], "claims_submit"),

    # ── 금융 > 생명 ──────────────────────────────────────────────────
    "167": S("contract_withdrawal_request",
             "사용자가 최근 가입한 보험 계약의 청약철회(취소)를 원할 때 사용합니다. 철회 가능 계약 확인 후 프로세스 진행에 적합합니다.",
             ["insurance_contract_inquiry", "contract_withdrawal_request"], "action_confirm"),
    "168": S("insurance_loan_inquiry",
             "사용자가 삼성생명에서 받은 대출 내역·잔액·금리·상환 진행 여부를 확인하려 할 때 사용합니다.",
             ["insurance_loan_inquiry"], "life_loan"),
    "169": S("insurance_loan_interest_date",
             "사용자가 보험계약대출의 이자 상환일이 언제인지 물을 때 사용합니다. 대출 잔액과 상환 일자 안내에 적합합니다.",
             ["insurance_loan_inquiry"], "life_loan"),
    "170": S("rate_cut_request_guide",
             "금리인하요구권 안내를 받은 사용자가 신청 메뉴·경로를 물을 때 사용합니다. 신청 가능 대상 상품과 신청 경로 안내에 적합합니다.",
             ["faq_search", "menu_search"], "menu"),
    "171": S("branch_search",
             "사용자가 보험 업무 대면 처리를 위해 가까운 지점/플라자를 찾을 때 사용합니다. 위치 확인 후 지점 정보(업무시간·전화번호·주차) 안내에 적합합니다.",
             ["branch_search"], "branch"),

    # ── 금융 > 화재 ──────────────────────────────────────────────────
    "173": S("cancellation_receipt_issue",
             "사용자가 보험 해지영수증·만기영수증 발급을 신청할 때 사용합니다. 발급 가능한 계약 목록 확인 후 발급 진행에 적합합니다.",
             ["insurance_contract_inquiry", "receipt_issue_request"], "action_confirm"),
    "174": S("auto_insurance_receipt_unavailable",
             "사용자가 자동차보험 해지영수증 발급을 신청할 때 사용합니다. 자동차보험은 해지영수증 발급이 불가능하다는 안내에 적합합니다.",
             ["insurance_contract_inquiry"], "guarded_error"),
    "201": S("virtual_account_inquiry",
             "사용자가 보험료 납부용 가상계좌번호를 물을 때 사용합니다.",
             ["virtual_account_inquiry"], "fire"),
    "202": S("temp_driver_contract_check",
             "사용자가 임시운전자 특약 가입을 위해 기존 가입 계약을 확인하려 할 때 사용합니다. 대상 계약 확인에 적합합니다.",
             ["insurance_contract_inquiry"], "fire"),
    "203": S("temp_driver_apply_period",
             "사용자가 임시운전자 특약 가입 기간을 직접 지정해 가입하려 할 때 사용합니다. 가입 기간·일수 확인 후 가입 진행에 적합합니다.",
             ["temp_driver_apply"], "action_confirm"),
    "204": S("temp_driver_status_inquiry",
             "사용자가 임시운전자 특약을 가입해 뒀는지 기가입 내역을 확인하려 할 때 사용합니다.",
             ["temp_driver_inquiry"], "fire"),

    # ── 금융 > 카드 ──────────────────────────────────────────────────
    "207": S("card_usage_inquiry",
             "사용자가 보유한 특정 카드의 이용내역을 물을 때 사용합니다. 최근 2주간 이용내역 안내에 적합합니다.",
             ["card_list_inquiry", "card_usage_inquiry"], "card"),
    "208": S("card_billing_amount_inquiry",
             "사용자가 이번 결제일에 얼마 나가는지 총 결제예정금액을 물을 때 사용합니다.",
             ["card_list_inquiry", "card_billing_inquiry"], "card"),
    "210": S("card_immediate_payment_by_amount",
             "사용자가 이번 달 카드 금액을 금액 기준으로 즉시결제하려 할 때 사용합니다. 결제예상금액 확인 후 즉시결제 실행에 적합합니다.",
             ["card_billing_inquiry", "card_immediate_payment"], "card_payment"),
    "211": S("card_immediate_payment_by_transaction",
             "사용자가 특정 이용 건을 골라 건별 즉시결제하려 할 때 사용합니다. 금액결제/건별결제 방식 비교 후 실행에 적합합니다.",
             ["card_usage_inquiry", "card_immediate_payment"], "card_payment"),
    "212": S("other_card_usage_inquiry",
             "사용자가 현대카드 등 타사 카드의 이용금액을 물을 때 사용합니다. 자산 > 소비내역(마이데이터) 기반 조회에 적합합니다.",
             ["other_card_usage_inquiry"], "card"),
    "214": S("other_card_payment_fallback",
             "사용자가 타사 카드의 즉시결제를 요청할 때 사용합니다. 타사 카드 결제는 해당 카드사에서만 가능함을 안내하고 이용내역 조회로 대체하는 경우에 적합합니다.",
             ["other_card_usage_inquiry"], "fallback"),

    # ── 금융 > 증권 ──────────────────────────────────────────────────
    "216": S("market_index_inquiry",
             "사용자가 오늘의 전반적인 주요 지수를 물을 때 사용합니다. 국내/해외 주요지수 안내에 적합합니다.",
             ["market_index_inquiry"], "index"),
    "217": S("domestic_index_inquiry",
             "사용자가 '오늘 국장 어때?'처럼 국내 주요지수를 물을 때 사용합니다. 지수 등락, 등락 종목 수, 대표 종목 안내에 적합합니다.",
             ["market_index_inquiry"], "index"),
    "218": S("overseas_index_inquiry",
             "사용자가 오늘 해외 주식·해외 주요지수 흐름을 물을 때 사용합니다.",
             ["market_index_inquiry"], "index"),
    "219": S("fx_rate_inquiry",
             "사용자가 오늘 환율이 어떤지 물을 때 사용합니다. 원달러 환율과 최근 일주일 등락 안내에 적합합니다.",
             ["market_index_inquiry"], "index"),
    "221": S("securities_system_guide",
             "사용자가 타사연금 이전 방법 등 삼성증권 시스템 이용 전반을 물을 때 사용합니다. 고객센터 연동 데이터 기반 안내에 적합합니다.",
             ["faq_search"], "faq"),
    "222": S("pb_consult_request",
             "사용자가 S.Lounge 전문PB 투자상담 서비스를 요청할 때 사용합니다. 대상 고객 여부 확인 후 진입점 안내에 적합합니다.",
             ["pb_consult_request"], "securities_service"),
    "223": S("pension_education_apply",
             "DC/IRP 가입 사용자가 퇴직연금 가입자교육 신청을 원할 때 사용합니다. 법정의무교육과 이수기간 안내에 적합합니다.",
             ["pension_education_apply"], "securities_service"),

    # ── 비금융 > 일상 > 생활 컨텐츠 ──────────────────────────────────
    "254": S("daily_fortune_no_profile",
             "사주정보를 입력하지 않은 사용자가 오늘의 운세를 물을 때 사용합니다. 사주정보 입력 유도 후 운세 안내에 적합합니다.",
             ["saju_profile_inquiry", "saju_profile_register", "fortune_inquiry"], "fortune"),
    "255": S("daily_fortune_inquiry",
             "사용자가 생년월일과 함께, 또는 사주정보 입력 완료 상태에서 오늘의 운세를 물을 때 사용합니다.",
             ["saju_profile_inquiry", "fortune_inquiry"], "fortune"),
    "256": S("love_fortune_inquiry",
             "사용자가 오늘의 사랑운 등 세부 운세를 물을 때 사용합니다.",
             ["saju_profile_inquiry", "fortune_inquiry"], "fortune"),
    "257": S("zodiac_fortune_inquiry",
             "사용자가 양띠 등 특정 띠의 오늘의 운세를 물을 때 사용합니다.",
             ["fortune_inquiry"], "fortune"),
    "258": S("tarot_inquiry",
             "사용자가 오늘의 타로카드·타로점을 요청할 때 사용합니다. 타로 서비스 설명과 화면 바로가기 제공에 적합합니다.",
             ["fortune_inquiry"], "fortune"),
    "259": S("tojeong_fortune_inquiry",
             "사용자가 신년 토정비결(신토정비결)을 요청할 때 사용합니다.",
             ["saju_profile_inquiry", "fortune_inquiry"], "fortune"),
    "261": S("wealth_fortune_inquiry",
             "사용자가 올해 재물운 등 사주 기반 세부 운세를 물을 때 사용합니다.",
             ["saju_profile_inquiry", "fortune_inquiry"], "fortune"),
    "262": S("compatibility_fortune_inquiry",
             "사용자가 연인·배우자와의 궁합을 보고 싶어할 때 사용합니다. 두 사람의 사주정보 기반 궁합 안내에 적합합니다.",
             ["saju_profile_inquiry", "fortune_inquiry"], "fortune"),
    "263": S("fortune_invalid_birth_fallback",
             "사용자가 미래 출생일 등 비정상적인 사주정보로 운세를 요청할 때 사용합니다. 사주정보 재확인 후 운세 안내에 적합합니다.",
             ["saju_profile_register", "fortune_inquiry"], "fallback"),
    "264": S("restaurant_content_recommend",
             "사용자가 맛집 추천 등 일상생활 질의를 했고, 대응 가능한 관심소식 콘텐츠가 있을 때 사용합니다. 여행맛집 카테고리 최근 게시물 요약 안내에 적합합니다.",
             ["content_list_inquiry"], "content"),

    # ── 비금융 > 미지원 질문 (가드레일) ──────────────────────────────
    "267": S("unsupported_abusive_language",
             "사용자가 욕설·혐오·폭력성·선정성 표현으로 질의한 경우 사용합니다. 정중한 제한 안내로 응답합니다.",
             [], "unsupported"),
    "268": S("unsupported_system_probe",
             "사용자가 모니모 AI Agent 시스템 내부(예: 시스템 프롬프트, 모델 구성)에 대해 질의한 경우 사용합니다.",
             [], "unsupported"),
    "269": S("unsupported_unintelligible_query",
             "과도한 오타 등으로 사용자 질의의 의도 파악이 불가능한 경우 사용합니다. 의도 재확인 요청으로 응답합니다.",
             [], "unsupported"),
    "270": S("unsupported_personal_info",
             "사용자가 본인 또는 타인의 개인정보(주민번호, 연락처 등)에 대해 질의한 경우 사용합니다.",
             [], "unsupported"),
    "271": S("unsupported_multimodal_generation",
             "사용자가 이미지·차트·보이스 등 멀티모달 생성을 요청한 경우 사용합니다.",
             [], "unsupported"),
    "272": S("unsupported_document_generation",
             "사용자가 문서·데이터 파일 생성을 요청한 경우 사용합니다.",
             [], "unsupported"),
    "273": S("unsupported_long_text_generation",
             "사용자가 1만 자 이상, 100가지 예시 등 과도한 장문의 텍스트 생성을 요청한 경우 사용합니다.",
             [], "unsupported"),
    "274": S("unsupported_repetition_request",
             "사용자가 동일 문장 반복 출력이나 투표 유도 등을 요청한 경우 사용합니다.",
             [], "unsupported"),
    "275": S("unsupported_low_value_generation",
             "사용자가 '아무 질문이나 해줘' 등 의미 없는 텍스트 생성을 요청한 경우 사용합니다.",
             [], "unsupported"),
    "276": S("unsupported_external_link",
             "사용자 질의에 외부 링크가 삽입된 경우 사용합니다. 외부 링크 내용은 처리하지 않음을 안내합니다.",
             [], "unsupported"),
    "277": S("unsupported_competitor_info",
             "사용자가 삼성금융 외 타사 정보(타 금융사 상품 등)에 대해 질의한 경우 사용합니다.",
             [], "unsupported"),
    "278": S("unsupported_copyright_request",
             "사용자가 노래 가사 등 저작권을 침해하는 내용을 요청한 경우 사용합니다.",
             [], "unsupported"),
    "279": S("unsupported_public_figure",
             "정치인·연예인 등 공인의 실명이 언급된 질의인 경우 사용합니다.",
             [], "unsupported"),
    "280": S("fallback_investment_advice",
             "사용자가 어떤 맥락에서든 '살까/팔까' 등 투자 의사결정을 질의한 경우 사용합니다. 의사결정 대신 객관적 정보 제공으로 대체 안내합니다.",
             [], "fallback"),
    "281": S("unsupported_internal_info",
             "사용자가 삼성금융 4사의 내부 정보(조직/인사/시스템/내부업무)를 질의한 경우 사용합니다.",
             [], "unsupported"),
    "282": S("fallback_product_recommend_decision",
             "사용자가 '어떤 상품이 제일 좋아?'처럼 단정적 상품 추천·선택 결정을 요청한 경우 사용합니다. 특정 상품 단정 대신 비교 정보 제공으로 대체 안내합니다.",
             [], "fallback"),
}
